on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/deploy.yml'
      - 'src/**'
      - 'test/**'
      - 'action.yml'
      - 'package-lock.json'
      - 'tsconfig.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  compile-action:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run build.types
      - uses: actions/upload-artifact@v3
        with:
          path: dist/**/*.js
          if-no-files-found: error
          retention-days: 1
