on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/deploy.yml'
      - 'src/**'
      - 'test/**'
      - 'action.yml'
      - 'package-lock.json'
      - 'tsconfig.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  compile-action:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run build.types
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**/*.js
          if-no-files-found: error
          retention-days: 1
  test-build-only:
    needs: compile-action
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
  test-publish:
    needs: compile-action
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/download-artifact@v3
      - run: tree .
        working-directory: dist
  test-publish_legacy_credentials:
    needs: compile-action
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
  test-publish_hardcoded_wrangler_version:
    needs: compile-action
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
  test-publish_secrets:
    needs: compile-action
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: step-security/harden-runner@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
  publish-action:
    needs: [test-build-only, test-publish, test-publish_legacy_credentials, test-publish_hardcoded_wrangler_version, test-publish_secrets]
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
