on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type'
        type: choice
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - name: Setup Git
        run: |
          git config --local user.name "DemosJarco"
          git config --local user.email "1209494+demosjarco@users.noreply.github.com"
      - run: npm version ${{ github.event.inputs.version }} -m "[ci skip] Triggered publish %s"
      - run: git push
      - run: git push --tags
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
